# Model configuration
MODEL: "OpenAI"  # The type of multi-modal LLM you would like to use to power the AppAgent, must be either OpenAI or Qwen

# OPENAI_API_BASE: "https://api.openai.com/v1/chat/completions"
OPENAI_API_BASE: "https://api.zhizengzeng.com/v1"
OPENAI_API_KEY: "sk-zk293317101239fff1d9f9f91612069fca66926b4775165f"  # Set the value to sk-xxx if you host the openai interface for open llm model
OPENAI_API_MODEL: "gpt-4o"
# OPENAI_API_MODEL: "gpt-4o"  # Changed from deprecated gpt-4-vision-preview to gpt-3.5-turbo
# OPENAI_API_BASE: "http://localhost:8001/v1"
# OPENAI_API_KEY: "qwerasdfzxcv123"
# OPENAI_API_MODEL: "autoglm-phone-9b-multilingual"
# OPENAI_API_MODEL: "qwen2.5-vl-7B-instruct"
# OPENAI_API_MODEL: "qwen3-vl-8B-instruct"
# OPENAI_API_MODEL: "GUI-Owl-7B"
# OPENAI_API_BASE: "https://dashscope.aliyuncs.com/compatible-mode/v1"
# OPENAI_API_KEY: "sk-4d34e688c7224c8d8a7753d7f419d752"
# OPENAI_API_MODEL: "qwen-vl-max"
OPENAI_CODE_API_MODEL: "qwen3-coder-plus"

LANG: "en"  # The language for the agent to operate in, currently only "en" (English) and "cn" (Chinese) is supported


MAX_TOKENS: 300  # The max token limit for the response completion
TEMPERATURE: 0.0  # The temperature of the model: the lower the value, the more consistent the output of the model
REQUEST_INTERVAL: 1  # Time in seconds between consecutive GPT-4V requests

# Android configuration

ANDROID_SCREENSHOT_DIR: "/sdcard"  # Set the directory on your Android device to store the intermediate screenshots. Make sure the directory EXISTS on your phone!
ANDROID_XML_DIR: "/sdcard"  # Set the directory on your Android device to store the intermediate XML files used for determining locations of UI elements on your screen. Make sure the directory EXISTS on your phone!

# Task configuration

MAX_ROUNDS: 50  # Set the round limit for the agent to complete the task
QUIET: false  # Set this to true to disable the verbose logging during the agent execution
ROOT: "./"
MEMORY_DIR: "./output/memory"  # The directory to store the agent's memory files, including work graphs and screenshots

DOC_REFINE: false  # Set this to true will make the agent refine existing documentation based on the latest demonstration; otherwise, the agent will not regenerate a new documentation for elements with the same resource ID.

DARK_MODE: false  # Set this to true if your app is in dark mode to enhance the element labeling
MIN_DIST: 30  # The minimum distance between elements to prevent overlapping during the labeling process




DASHSCOPE_API_KEY: "sk-4d34e688c7224c8d8a7753d7f419d752"  # The dashscope API key that gives you access to Qwen-VL model
QWEN_MODEL: "qwen-vl-max"
# QWEN_MODEL: "qwen3-vl-plus"